# ── Stage 1: Base ────────────────────────────────────────────────────────────
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./

# ── Stage 2: Development dependencies ─────────────────────────────────────────
FROM base AS development-deps
RUN npm ci

# ── Stage 3: Production dependencies ──────────────────────────────────────────
FROM base AS production-deps
RUN npm ci --omit=dev

# ── Stage 4: Development stage ────────────────────────────────────────────────
FROM node:20-alpine AS development
WORKDIR /app
COPY --from=development-deps /app/node_modules ./node_modules
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# ── Stage 5: Build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS build
WORKDIR /app
COPY --from=development-deps /app/node_modules ./node_modules
COPY . .

# Build-time ARGs — baked into the bundle as fallback defaults.
# At runtime these are overridden by window.__RUNTIME_CONFIG__ from env-config.js
# (generated by start_production.sh from Azure Key Vault or environment variables).
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_DEV_MODE=false
ARG VITE_API_DEBUG=false

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_DEV_MODE=$VITE_DEV_MODE
ENV VITE_API_DEBUG=$VITE_API_DEBUG

# Increase Node.js heap to prevent OOM during Rollup bundling of large codebases
ENV NODE_OPTIONS=--max-old-space-size=4096

RUN npm run build

# ── Stage 6: Production (Nginx + Azure Key Vault startup) ─────────────────────
FROM nginx:1.27-alpine AS production
WORKDIR /usr/share/nginx/html

# bash + curl + jq required by start_production.sh:
#   curl  — fetches IMDS token and Key Vault secrets
#   jq    — parses JSON responses reliably
RUN apk add --no-cache bash curl jq

# Remove default nginx assets
RUN rm -rf ./*

# Copy built assets (vite outputs to build/)
COPY --from=build /app/build .

# Inline nginx config — TLS and host routing are handled by the ingress controller
RUN printf 'server {\n\
    listen 80;\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
    location / {\n\
        try_files $uri $uri/ /index.html;\n\
    }\n\
    location = /health {\n\
        access_log off;\n\
        return 200 "ok";\n\
        add_header Content-Type text/plain;\n\
    }\n\
    location ~* \\.(?:js|css|woff2?|svg|png|jpg|ico)$ {\n\
        expires 1y;\n\
        add_header Cache-Control "public, immutable";\n\
    }\n\
}\n' > /etc/nginx/conf.d/default.conf

# Startup script: fetches secrets from Azure Key Vault, writes env-config.js,
# then execs nginx
COPY scripts/start_production.sh /usr/local/bin/start_production.sh
RUN chmod +x /usr/local/bin/start_production.sh

# Default env vars (overridden at runtime by Key Vault or pod env)
ENV VITE_FIREBASE_API_KEY="" \
    VITE_FIREBASE_AUTH_DOMAIN="" \
    VITE_FIREBASE_PROJECT_ID="" \
    VITE_FIREBASE_STORAGE_BUCKET="" \
    VITE_FIREBASE_MESSAGING_SENDER_ID="" \
    VITE_FIREBASE_APP_ID="" \
    VITE_DEV_MODE="false" \
    VITE_API_DEBUG="false"

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:80/health || exit 1

ENTRYPOINT ["/usr/local/bin/start_production.sh"]
