# ── Stage 1: Development ──────────────────────────────────────────────────────
# Kept for local `docker compose up` — not used in the CI pipeline.
FROM node:20-alpine AS development
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# ── Stage 2: Build ────────────────────────────────────────────────────────────
# Key memory optimisations for constrained self-hosted agents:
#   1. Single RUN for install+build — BuildKit discards the layer's COW diff
#      as soon as the RUN finishes, instead of keeping two fat layers resident.
#   2. --optimize-for-size tells V8 to favour smaller heap over throughput.
#   3. --gc-interval=100 forces a GC check every 100 allocations (default 4096),
#      catching garbage from Rollup's transform phase much earlier.
#   4. --max-semi-space-size=16 keeps the nursery tiny (default ~16 MB on 20.x
#      but explicit here for clarity).
#   5. The manual-chunk config in vite.config.ts splits the bundle so Rollup
#      can serialise and release each chunk independently.
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
COPY . .

# Build-time ARGs — baked into the bundle as fallback defaults.
# At runtime these are overridden by window.__RUNTIME_CONFIG__ from env-config.js
# (generated by start_production.sh from Azure Key Vault or environment variables).
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_DEV_MODE=false
ARG VITE_API_DEBUG=false

ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_DEV_MODE=$VITE_DEV_MODE \
    VITE_API_DEBUG=$VITE_API_DEBUG

# Single RUN: install + build + clean — keeps only build/ artefacts in the layer
ENV NODE_OPTIONS="--max-old-space-size=2560 --max-semi-space-size=16 --optimize-for-size --gc-interval=100"
RUN npm ci && \
    npm run build && \
    rm -rf node_modules

# ── Stage 3: Production (Nginx + Azure Key Vault startup) ─────────────────────
FROM nginx:1.27-alpine AS production
WORKDIR /usr/share/nginx/html

# bash + curl + jq required by start_production.sh:
#   curl  — fetches IMDS token and Key Vault secrets
#   jq    — parses JSON responses reliably
RUN apk add --no-cache bash curl jq

# Remove default nginx assets
RUN rm -rf ./*

# Copy pre-built assets from the build stage (vite outputs to build/)
COPY --from=build /app/build .

# Inline nginx config — TLS and host routing are handled by the ingress controller
RUN printf 'server {\n\
    listen 80;\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
    location / {\n\
        try_files $uri $uri/ /index.html;\n\
    }\n\
    location = /health {\n\
        access_log off;\n\
        return 200 "ok";\n\
        add_header Content-Type text/plain;\n\
    }\n\
    location ~* \\.(?:js|css|woff2?|svg|png|jpg|ico)$ {\n\
        expires 1y;\n\
        add_header Cache-Control "public, immutable";\n\
    }\n\
}\n' > /etc/nginx/conf.d/default.conf

# Startup script: fetches secrets from Azure Key Vault, writes env-config.js,
# then execs nginx
COPY scripts/start_production.sh /usr/local/bin/start_production.sh
RUN chmod +x /usr/local/bin/start_production.sh

# Default env vars (overridden at runtime by Key Vault or pod env)
ENV VITE_FIREBASE_API_KEY="" \
    VITE_FIREBASE_AUTH_DOMAIN="" \
    VITE_FIREBASE_PROJECT_ID="" \
    VITE_FIREBASE_STORAGE_BUCKET="" \
    VITE_FIREBASE_MESSAGING_SENDER_ID="" \
    VITE_FIREBASE_APP_ID="" \
    VITE_DEV_MODE="false" \
    VITE_API_DEBUG="false"

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:80/health || exit 1

ENTRYPOINT ["/usr/local/bin/start_production.sh"]
