import { mock } from '../MockAdapter'
import { chatHistoryData, imageData, generatedImageData } from '../data/aiData'
import uniqueId from 'lodash/uniqueId'
import dayjs from 'dayjs'

mock.onGet(`/api/ai/chat/history`).reply(() => {
    return [200, chatHistoryData]
})

mock.onPost(`/api/ai/chat`).reply((config) => {
    const { prompt } = JSON.parse(config.data as string) as { prompt: string }

    const userPrompt = prompt.toLocaleLowerCase()
    console.log('userPrompt', userPrompt)
    const responseContents = {
        regular: [
            // `This is a mock response designed to simulate an AI-generated reply. Please note that this response is not generated by an actual AI model. You can include 'cytokine', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
            `Hello! Dive into the ever-evolving world of medical and clinical research with me. Ask me anything about the latest trends, groundbreaking discoveries, and cutting-edge  developments shaping the future of healthcare. Let me simplify the complexities and make your journey through innovation effortless`,
            // `For demo purposes, this response is a mock message. It showcases what a typical AI reply might look like, but it is not produced by a real AI. You can include 'cytokine', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
            // `This mock response is part of a demonstration and is not generated by an actual AI. The content here is pre-defined for showcasing purposes. You can include 'cytokine', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
            // `As part of this demo, you are viewing a mock response. This text is not created by an AI model, but rather a pre-written example to illustrate functionality. You can include 'cytokine', 'code', 'list' keywords in your prompt to get different kinds of mock responses.`,
        ],
        cytokine: 'This is a detailed response on cytokine release syndrome.\n\n###### Cytokine Release Syndrome Associated with T-Cell-Based Therapies for Hematological Malignancies: Pathophysiology, Clinical Presentation, and Treatment\n\nCytokine release syndrome (CRS) is a significant concern in T-cell-based therapies for hematological malignancies. It is associated with severe immune responses and can lead to complications such as respiratory distress. The syndrome has been observed in patients receiving PD-1-directed therapy and CAR T cell immunotherapy. Therapeutic T cell engineering is being explored to mitigate adverse effects and improve patient outcomes.\nURL: https://pubmed.ncbi.nlm.nih.gov/34299273/\n\n###### Cytokine Release Syndrome in COVID-19 Patients: A New Scenario for an Old Concern - The Fragile Balance between Infections and Autoimmunity\n\nCRS is a systemic inflammatory condition that has gained attention due to its occurrence in COVID-19 patients. It results from a cytokine storm and can be life-threatening, requiring intensive care. Initially noted as a reaction to anti-CD3 monoclonal antibody use, CRS is now a concern in SARS-CoV-2 infections. Immunosuppressive agents, commonly used in autoimmune diseases, are being considered for treating CRS in COVID-19 patients.\nURL: https://pubmed.ncbi.nlm.nih.gov/32397174/\n\n###### Cytokine Release Syndrome and Associated Neurotoxicity in Cancer Immunotherapy\n\nCRS in COVID-19 patients has similarities to acute respiratory distress syndrome (ARDS) seen in other conditions. It involves cytokine hypersecretion, dysregulated macrophage activation, and lymphopenia, leading to cardiovascular effects. Respiratory support, such as intubation, may be necessary. Recent studies highlight the significant immune complications in COVID-19 that resemble CRS-related ARDS, underscoring the need for targeted therapeutic strategies.\nURL: https://pubmed.ncbi.nlm.nih.gov/34002066/\n\nKeywords: Cytokine release syndrome, T-cell-based therapies, COVID-19, cytokine storm, immunotherapy, acute respiratory distress syndrome, immunosuppressive agents.',
        pathways: 'This is a detailed response on cytokine release syndrome.\n\n###### Signaling Pathways in the Regulation of Cytokine Release Syndrome in Human Diseases and Intervention Therapy\n\nRecent trends in cytokine release syndrome (CRS) pathways emphasize the integration of advanced technologies to address challenges such as CAR-T cell expansion and exhaustion. The review suggests that single-cell multiomics, including CAR-T-cell integration site analysis, scRNA-seq, scATAC-seq, CyTOF, and imaging technologies, should be utilized for comprehensive CRS studies. CRS is considered a double-edged sword, aiding disease control but potentially harmful to the host. The aim is to understand CRS mechanisms in human diseases to achieve effective treatment with minimal toxicity. The review highlights the clinical features, kinetics, signaling pathways, and potential mechanisms of CRS, underscoring its clinical significance.\nURL: https://pubmed.ncbi.nlm.nih.gov/34667157/\n\n###### Cytokine Release Syndrome Associated with T-Cell-Based Therapies for Hematological Malignancies: Pathophysiology, Clinical Presentation, and Treatment\n\nThe management of CRS in T-cell-based therapies for hematological malignancies involves multidisciplinary collaboration among hematologists, neurologists, radiologists, and intensive care specialists. Effective management strategies currently include early intervention and the use of tocilizumab and corticosteroids. Despite existing grading scales and treatment algorithms, new insights into CRS pathophysiology are needed to develop more effective treatments.\nURL: https://pubmed.ncbi.nlm.nih.gov/34299273/\n\n###### Signaling Pathways in the Regulation of Cytokine Release Syndrome in Human Diseases and Intervention Therapy\n\nRecent trends in cytokine release syndrome (CRS) pathways emphasize the integration of advanced technologies to address challenges such as CAR-T cell expansion and exhaustion. The review suggests that single-cell multiomics, including CAR-T-cell integration site analysis, scRNA-seq, scATAC-seq, CyTOF, and imaging technologies, should be utilized for comprehensive CRS studies. CRS is considered a double-edged sword, aiding disease control but potentially harmful to the host. The aim is to understand CRS mechanisms in human diseases to achieve effective treatment with minimal toxicity. The review highlights the clinical features, kinetics, signaling pathways, and potential mechanisms of CRS, underscoring its clinical significance.\nURL: https://pubmed.ncbi.nlm.nih.gov/34667157/\n\n###### Cytokine Release Syndrome Associated with T-Cell-Based Therapies for Hematological Malignancies: Pathophysiology, Clinical Presentation, and Treatment\n\nThe management of CRS in T-cell-based therapies for hematological malignancies involves multidisciplinary collaboration among hematologists, neurologists, radiologists, and intensive care specialists. Effective management strategies currently include early intervention and the use of tocilizumab and corticosteroids. Despite existing grading scales and treatment algorithms, new insights into CRS pathophysiology are needed to develop more effective treatments.\nURL: https://pubmed.ncbi.nlm.nih.gov/34299273/\n\nKeywords: Recent trends in CRS pathways focus on advanced technologies, multidisciplinary collaboration, CAR-T cell challenges, single-cell multiomics, and effective management strategies.',
        Neurotoxicity: 'This is a detailed response on cytokine release syndrome.\n\n###### Cytokine Release Syndrome Associated with T-Cell-Based Therapies for Hematological Malignancies: Pathophysiology, Clinical Presentation, and Treatment\n\nSevere viral infections, such as influenza and SARS-CoV-2 (COVID-19), can trigger Cytokine Release Syndrome (CRS) through massive immune and non-immune cell stimulation. Immunotherapy approaches, including immune checkpoint inhibition and T-cell-engaging therapies like bispecific T-cell-engaging (BiTE) single-chain antibody constructs and chimeric antigen receptor (CAR) T cells, have advanced cancer treatment. However, CRS is a significant adverse effect of these therapies. Therapeutic T cell engineering is being explored to mitigate adverse effects and improve patient outcomes.\nURL: https://pubmed.ncbi.nlm.nih.gov/34299273/\n\n###### Cytokine Release Syndrome and Associated Neurotoxicity in Cancer Immunotherapy\n\nThe risk-benefit balance of potentially toxic therapies necessitates improved management of toxicities or the development of therapies with lower toxicity profiles. Understanding the clinical features and pathophysiological mechanisms of CRS and Immune Effector Cell-Associated Neurotoxicity Syndrome (ICANS) is crucial for developing novel therapeutics. CRS and ICANS also have broader implications for other systemic, cytokine-mediated inflammatory diseases, such as septic shock, macrophage activation syndrome, neuroinflammatory disease, and infections with emerging pathogens like SARS-CoV-2.\nURL: https://pubmed.ncbi.nlm.nih.gov/34002066/\n\n###### Cell-Based Models of Cytokine Release Syndrome Endorse CD40L and Granulocyte Macrophage Colony Stimulating Factor Knockout in Chimeric Antigen Receptor T Cells as Mitigation Strategy\n\nCAR T-cell therapies are effective for treating hematologic malignancies but can cause severe side effects, including on-target/off-tumor toxicity, neurotoxicity, and CRS. CRS occurs when tumor-activated CAR T cells stimulate bystander immune cells, primarily myeloid cells, to release large amounts of proinflammatory cytokines, especially IL-6. Cell-based models that simulate the complex in vivo environment help identify key regulators in CRS, offering potential strategies for local prevention and treatment.\nURL: https://pubmed.ncbi.nlm.nih.gov/37947658/\n\n###### Cytokine Release Syndrome Associated with T-Cell-Based Therapies for Hematological Malignancies: Pathophysiology, Clinical Presentation, and Treatment\n\nSevere viral infections, such as influenza and SARS-CoV-2 (COVID-19), can trigger Cytokine Release Syndrome (CRS) through massive immune and non-immune cell stimulation. Immunotherapy approaches, including immune checkpoint inhibition and T-cell-engaging therapies like bispecific T-cell-engaging (BiTE) single-chain antibody constructs and chimeric antigen receptor (CAR) T cells, have advanced cancer treatment. However, CRS is a significant adverse effect of these therapies. Therapeutic T cell engineering is being explored to mitigate adverse effects and improve patient outcomes.\nURL: https://pubmed.ncbi.nlm.nih.gov/34299273/\n\nKeywords: Cytokine Release Syndrome, Neurotoxicity, CAR T-cell, Immunotherapy, Hematological Malignancies, IL-6, SARS-CoV-2.',
    }

    let content =
        responseContents.regular[
            Math.floor(Math.random() * responseContents.regular.length)
        ]

    if (userPrompt.includes('cytokine')) {
        content = responseContents.cytokine
    }
    if (userPrompt.includes('pathways')) {
        content = responseContents.pathways
    }
    if (userPrompt.includes('Neurotoxicity')) {
        content = responseContents.Neurotoxicity
    }

    const response = {
        id: uniqueId('ai-conversation-'),
        choices: [
            {
                finish_reason: 'stop',
                index: 0,
                message: {
                    content: content,
                    role: 'assistant',
                },
            },
        ],
        created: dayjs().unix(),
        model: 'gpt-4',
    }

    return new Promise(function (resolve) {
        setTimeout(function () {
            resolve([200, response])
        }, 800)
    })
})

mock.onGet(`/api/ai/images`).reply((config) => {
    const { index, itemCount = 4 } = config.params

    let loadable = true
    const maxGetItem = itemCount
    const count = (index - 1) * maxGetItem
    let images = imageData
    if (count >= images.length) {
        loadable = false
    }
    images = images.slice(count, index * maxGetItem)
    const response = {
        data: images,
        loadable,
    }
    return [200, response]
})

mock.onPost(`/api/ai/images`).reply((config) => {
    const { prompt } = JSON.parse(config.data as string) as { prompt: string }

    const imageSet = generatedImageData[
        Math.floor(Math.random() * generatedImageData.length)
    ].map((img) => {
        img.prompt = prompt
        return img
    })

    return new Promise(function (resolve) {
        setTimeout(function () {
            resolve([200, imageSet])
        }, 2000)
    })
})
